title = "ITエンジニアパパの奮闘記"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "ja"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
#`resourceDir = "../resources"

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

#[languages]
#  [languages.en]
#    title = ""
#    weight = 1
#    contentDir = "content/en"
#    # languageDirection = 'rtl' for Right-To-Left languages
#  [languages.fr]
#    title = "Ananke Fr"
#    weight = 2
#    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "hakupapa"
  favicon = ""
  site_logo = ""
  description = "はくパパエンジニアの奮闘記"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/hakupappa3"
