title = "はくパパブログ"
baseURL = "https://hakupapa46.github.io/blog"
languageCode = "ja"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "hakupapa"
  favicon = ""
  site_logo = ""
  description = "はくパパブログ"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/hakupappa3"
